### ISSUE TITLE
Some textures are missing

### ISSUE THREAD

**Issue by wildbill22** [TheXFactor117/Ascension#15]
When starting eclipse, errors for these textures are seen:
textures/items/infusedVexalSword.png - this file missing from textures/items folder.
textures/items/infusedVexalIngot.png - missing

**Comment by TheXFactor117** [comment]
Thanks for the in-depth detail. I'll be referencing this every now and then, and will check off some of these.

**Comment by TheXFactor117** [comment]
Updated missing texture list.

**Comment by TheXFactor117** [comment]
Updated list again.

**Comment by TheXFactor117** [comment]
Added the last two textures.
