### ISSUE TITLE
registerModEntity should use a unique mod Id, not global Id

### ISSUE THREAD

**Issue by wildbill22** [TheXFactor117/Ascension#24]
For instance, in registerMonsters it calls registerModEntity, and uses an entityId from findGlobalUniqueEntityId().

**Comment by TheXFactor117** [comment]
I'd have to look into it a bit more; do you have any suggestions of the top of your head? I also don't see what necessarily is wrong.

**Comment by wildbill22** [comment]
It is a bit complicated, because you have this extra function called registerMonsters, but if all the calls to registerModEntity occur in one location, then you just initialize a static variable to 0 (modEntityId for example, then when you use the variable, use it like this: "++modEntityId". That ensures the first time you use it is 1, and each time after increments and gives a unique (in the mod) id for each entity that is created. You stop using the findGlobalUniqueEntityId() function for Ids that are used in registerModEntity().

**Comment by TheXFactor117** [comment]
I see a bit better now. I may just rewrite the ModEntities class to include the Pharaoh (so we can remove the ModBosses class), and to register the entities how I'm registering the Pharaoh (which allows me to customize the spawn eggs a bit more.

**Comment by TheXFactor117** [comment]
I'm going to start re-writing how entities are registered to switch everything over to registerModEntity instead of Global.

**Comment by TheXFactor117** [comment]
And its implemented.
