### ISSUE TITLE
Crash Banshee

### ISSUE THREAD

**Issue by Cronosus** [TheXFactor117/Ascension#27]
game crash
http://pastebin.com/DWfyF7Db

what about add to config option to disable some mobs and items?

**Comment by TheXFactor117** [comment]
I'll look into that crash later today. Was it just a one time thing or does it keep happening?

I'm working on the config to make it highly customizable. I'll add options to disable certain mobs as well.

**Comment by Cronosus** [comment]
it happens repeately, when i create world, after while close and open again.. crashing

**Comment by TheXFactor117** [comment]
I've figured out what is causing the issue. I'll test with it a bit and see if I can fix it.

Can you load up a super flat world a spawn a Banshee in and see if it crashes? Same thing with the Ghost as well.

**Comment by TheXFactor117** [comment]
I just pushed an update which will potentially fix the error. Get it here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2361657-b1-2-3-ascension-an-immersive-challenging

If it still is bugging out, create a new issue.
