### ISSUE TITLE
Mob Spawner's in structures don't spawn mobs

### ISSUE THREAD

**Issue by wildbill22** [TheXFactor117/Ascension#30]
For example, in the SmallAbandonedHouse, no mobs spawn. Originally the Ghost was named "Ghost", but now an ItemAscensionMonsterPlacer class adds Reference.MODID + "." to the "Ghost" name, so the full name of "thexfactor117_ascension.Ghost" is needed. 

Not sure of the best fix at this point.

**Comment by TheXFactor117** [comment]
I added a variable to each entity called "name", along with a getter for name. This is only in the 1.8 version, as I don't really have plans for releasing Beta 2 for 1.7.10 alongside 1.8.

Let me know if this will work for you.
